### ISSUE TITLE
hard-code to ignore the `action-testing` repo

### ISSUE THREAD

**Issue by aturley** [ponylang/pony-sync-helper#1]
@SeanTAllen has suggested that we hard code to ignore the `action-testing` because it is there for testing actions and there will never be an issue in there that needs to be discussed.

I'm not sure I want to hard-code this because in the off chance that this requirement ever does change (ie some day there are issues in this repo we're interested in) it might not be immediately obvious why it  doesn't show up in the list. I'd rather ignore it in the meeting or add an `--exclude` flag that let's the user specify repos that should be ignored by the program.

**Comment by SeanTAllen** [comment]
not needed anymore as we now look for a specific label and can avoid adding it to repos we dont want to display items for.
